name: "Image: cf-acceptance-tests"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cf-acceptance-tests/**"
      - ".github/workflows/cf-acceptance-tests.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: cf-acceptance-tests
